/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ripenol_Bottle_1.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Label: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Ripenol_Bottle_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0, 1.358, 0.001]} rotation={[0, -0.733, 0]} scale={0.776} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Label} position={[0, 1.358, 0.001]} rotation={[0, -0.733, 0]} scale={0.776} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[0, 1.358, 0.001]} rotation={[0, -0.733, 0]} scale={0.776} />
    </group>
  )
}

useGLTF.preload('/Ripenol_Bottle_1.glb')
